# Generated by Django 4.1.3 on 2024-07-30 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trackerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
    ]
