# Generated by Django 4.1.3 on 2024-07-31 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Trackerapp', '0004_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='income_source',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Trackerapp.income'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
